version: "3.8"

services:
  employee-app:
    container_name: employee_container
    build: .
    ports:
      - "9090:9090"
    environment:
      SERVER_PORT: 9090
      DB_PORT: 5432
      DB_PASSWORD: 1234
      DB_USERNAME: elyor
      DB_NAME: employee
      DB_HOST: postgres_db_container
    depends_on:
      - postgres
    restart: always
  postgres:
    image: postgres:latest
    container_name: postgres_db_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: elyor
      POSTGRES_DB: employee
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
  pgAdmin:
    restart: always
    image: dpage/pgadmin4
    container_name: pg-Admin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: elyor@gmail.com
      PGADMIN_DEFAULT_PASSWORD: elyor1202
    depends_on:
      - postgres

volumes:
  postgres_data: {}
