server:
  port: ${SERVER_PORT:8080}
spring:
  application:
    name: spring-with-docker
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:dpg-cl5r18s72pts73es12r0-a.oregon-postgres.render.com}:${DB_PORT:5432}/${DB_NAME:docker_2i5s}
    password: ${DB_PASSWORD:vNxr5ZhOGJQCkTqXCrCSsKJl88iKDGqN}
    username: ${DB_USERNAME:elyor}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

