server:
  port: ${SERVER_PORT:8080}
spring:
  application:
    name: spring-with-docker
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://roundhouse.proxy.rlwy.net:35520/railway
    password: 6FfG2d6df6FDAG5dDcfA1D4C6De25*5d
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

